name: Github Issue Tracker

on:
  issues:
    types: [opened]

jobs:
  ingestJob:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Algolia Record
        uses: chuckmeyer/add-algolia-record@v0
        with:
          app_id: ${{ secrets.ALGOLIA_APP_ID }}
          api_key: ${{ secrets.ALGOLIA_API_KEY }}
          index_name: ${{ github.event.repository.name }}
          record: |
            {
              "title": "${{ github.event.issue.title }}", 
              "url": "${{ github.event.issue.html_url }}", 
              "labels": "${{ github.event.issue.labels }}",
              "objectID": "${{ github.event.issue.number }}"
            }
  relatedSearch:
    runs-on: ubuntu-latest
    steps:
      - name: Search based on issue title
        uses: brob/algolia-issue-search@v1.0
        with:
          app_id: ${{ secrets.ALGOLIA_APP_ID }}
          api_key: ${{ secrets.ALGOLIA_API_KEY }}
          index_name: ${{ github.event.repository.name }}
          issue_title: ${{ github.event.issue.title }}
  commentIssue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ github.token }}
          issue-number: ${{github.event.issue.number}}
          body: "Add this comment"
