name: Github Issue Tracker

on:
  issues:
    types: [opened]

jobs:
  ingestJob:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello World"
  relatedSearch:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello World"
  commentIssue:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello World"
