name: Github Issue Tracker

on:
  issues:
    types: [opened]

jobs:
  validate-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: npm install
        run: npm run build

      - uses: actions/github-script@v7
        with:
          github-token: ${{secrets.Token}}
          script: |
            const issueBody = context.issue.body;
            require('./dist/template-check.js')(issueBody)
