name: Github Issue Tracker

on:
  issues:
    types: [opened]

jobs:
  ingestJob:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello World"
  relatedSearch:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello World"
  commentIssue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ github.token }}
          issue-number: ${{github.event.issue.number}}
          body: "Add this comment"
